/**
 * Matériels du barème Excel, un nom = un enregistrement.
 * Les libellés séparés par « / » sont scindés.
 * Utilisé par le seed uniquement — le client ne lit pas cette liste.
 */
export const SEED_MATERIALS: Array<{
  category: string
  name: string
  image: string
  points: number
  unit: string
  remarks: string | null
}> = [
  {
    category: "Téléphonie & Tablettes",
    name: "Smartphone tactile",
    image: "/materials/smartphone-tactile.jpg",
    points: 25,
    unit: "Pièce",
    remarks: "Reconditionnement si fonctionnel, recyclage sinon",
  },
  {
    category: "Téléphonie & Tablettes",
    name: "Téléphone à touches",
    image: "/materials/telephone-a-touches.jpg",
    points: 5,
    unit: "Pièce",
    remarks: "Recyclage et récupération métaux",
  },
  {
    category: "Téléphonie & Tablettes",
    name: "Tablette",
    image: "/materials/tablette.jpg",
    points: 40,
    unit: "Pièce",
    remarks: "Reconditionnement si fonctionnel",
  },
  {
    category: "Informatique",
    name: "Ordinateur portable",
    image: "/materials/ordinateur-portable.jpg",
    points: 75,
    unit: "Pièce",
    remarks: "Reconditionnement ou recyclage",
  },
  {
    category: "Informatique",
    name: "Ordinateur de bureau",
    image: "/materials/ordinateur-de-bureau.jpg",
    points: 60,
    unit: "Pièce",
    remarks: "Recyclage et récupération cuivre, alu",
  },
  {
    category: "Informatique",
    name: "Clavier",
    image: "/materials/clavier.jpg",
    points: 5,
    unit: "Pièce",
    remarks: "Recyclage plastique + circuits",
  },
  {
    category: "Informatique",
    name: "Souris",
    image: "/materials/souris.jpg",
    points: 5,
    unit: "Pièce",
    remarks: "Recyclage plastique + circuits",
  },
  {
    category: "Informatique",
    name: "Imprimante",
    image: "/materials/imprimante.jpg",
    points: 25,
    unit: "Pièce",
    remarks: "Retirer cartouches avant dépôt",
  },
  {
    category: "Informatique",
    name: "Disque dur",
    image: "/materials/disque-dur.jpg",
    points: 15,
    unit: "Pièce",
    remarks: "Destruction sécurisée possible",
  },
  {
    category: "Informatique",
    name: "SSD",
    image: "/materials/ssd.jpg",
    points: 15,
    unit: "Pièce",
    remarks: "Destruction sécurisée possible",
  },
  {
    category: "Informatique",
    name: "Routeur",
    image: "/materials/routeur.jpg",
    points: 50,
    unit: "Pièce",
    remarks: "Recyclage circuits",
  },
  {
    category: "Informatique",
    name: "Box",
    image: "/materials/box.jpg",
    points: 50,
    unit: "Pièce",
    remarks: "Recyclage circuits",
  },
  {
    category: "Informatique",
    name: "Modem",
    image: "/materials/modem.jpg",
    points: 50,
    unit: "Pièce",
    remarks: "Recyclage circuits",
  },
  {
    category: "Batteries & Accumulateurs",
    name: "Batterie lithium-ion",
    image: "/materials/batterie-lithium-ion.jpg",
    points: 5,
    unit: "Pièce",
    remarks: "Filière : MG Batteries (Ouganda). Danger si endommagée",
  },
  {
    category: "Batteries & Accumulateurs",
    name: "Batterie plomb-acide",
    image: "/materials/batterie-plomb-acide.jpg",
    points: 25,
    unit: "Pièce",
    remarks: "SOTRAFER RDC. Liquide à sécuriser",
  },
  {
    category: "Batteries & Accumulateurs",
    name: "Pile alcaline (non rechargeable)",
    image: "/materials/pile-alcaline.jpg",
    points: 5,
    unit: "Pièce",
    remarks: "Recyclage. Attention au mercure",
  },
  {
    category: "Câbles & Accessoires",
    name: "Chargeur",
    image: "/materials/chargeur.jpg",
    points: 5,
    unit: "Pièce",
    remarks: "Recyclage circuits + plastique",
  },
  {
    category: "Câbles & Accessoires",
    name: "Adaptateur",
    image: "/materials/adaptateur.jpg",
    points: 5,
    unit: "Pièce",
    remarks: "Recyclage circuits + plastique",
  },
  {
    category: "Petit électroménager",
    name: "Fer à repasser",
    image: "/materials/fer-a-repasser.jpg",
    points: 10,
    unit: "Pièce",
    remarks: "Recyclage métal + plastique",
  },
  {
    category: "Petit électroménager",
    name: "Ventilateur",
    image: "/materials/ventilateur.jpg",
    points: 10,
    unit: "Pièce",
    remarks: "Recyclage",
  },
  {
    category: "Petit électroménager",
    name: "Radio",
    image: "/materials/radio.jpg",
    points: 5,
    unit: "Pièce",
    remarks: "Recyclage",
  },
  {
    category: "Petit électroménager",
    name: "Lecteur CD",
    image: "/materials/lecteur-cd.jpg",
    points: 5,
    unit: "Pièce",
    remarks: "Recyclage",
  },
  {
    category: "Petit électroménager",
    name: "Grille-pain",
    image: "/materials/grille-pain.jpg",
    points: 10,
    unit: "Pièce",
    remarks: "Recyclage",
  },
  {
    category: "Petit électroménager",
    name: "Cafetière",
    image: "/materials/cafetiere.jpg",
    points: 10,
    unit: "Pièce",
    remarks: "Recyclage",
  },
  {
    category: "Audiovisuel & Divertissement",
    name: "Décodeur TV (Canal+, TNT)",
    image: "/materials/decodeur-tv.jpg",
    points: 15,
    unit: "Pièce",
    remarks: "Canal+ : décodeurs déclassés valorisables",
  },
  {
    category: "Cartes bancaires",
    name: "Carte bancaire expirée",
    image: "/materials/carte-bancaire-expiree.jpg",
    points: 5,
    unit: "Pièce",
    remarks: "Equity BCDC, Rawbank, Ecobank. Destruction sécurisée",
  },
]
